person:
#   单引号会将\n作为字符串输出 双引号会将\n作为换行符
#   双引号不会转义，单引号会转义
  boss: true
  birth: 2019/12/9
  age: 18
# interests: [篮球，足球]
  interests:
    - 篮球
    - 足球
    - 18
  animal: [阿猫,阿狗]
#  score:
#    english: 80
#    math: 90
  score: {english:80,math:90}
  salarys:
    - 9999.98
    - 9999.99
  pet:
    name: 啊狗
    weight: 99.99
  allPets:
    sick:
      - {name: 啊狗,weight: 99.99}
      - name: 啊猫
        weight: 88.88
      - name: 啊虫
        weight: 77.77
    health:
      - { name: 啊花,weight: 199.99 }
      - { name: 啊明,weight: 199.99 }
  user-name: zhangsan

#spring:
#  banner:
#    location:
#    image:
#      bitdepth: 4
#  cache:
#    type: redis
#    redis:
#      time-to-live: 11000