spring:
  datasource:
    url: jdbc:mysql://localhost:3306/background_system?serverTimezone=UTC
    username: root
    password: xuexi123.

    druid:
      aop-patterns: com.yillint.admin.* #监控SpringBean
      filters: stat,wall,slf4j           #底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:  #配置监控页功能
        enabled: true
        login-username: admin
        login-password: xuexi123.
        reset-enable: false

      web-stat-filter:  #监控Web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat: #对上面的filters的stat的详细配置
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    type: com.zaxxer.hikari.HikariDataSource


#  redis:
#    host: r-bp109yznzckbvfzdoepd.redis.rds.aliyuncs.com
#    port: 6379
#    password: yillint:YilLint123456
#    client-type: jedis
#    jedis:
#      pool:
#        max-active: 10
  #    url: redis://yillint:YilLint123456@r-bp1s00l30cvv0ha3dgpd.redis.rds.aliyuncs.com:6379
#    lettuce:
#      pool:
#        max-active: 10
#        min-idle: 5


  jdbc:
    template:
      query-timeout: 3
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true #使用ip注册进来

  application:
    name: boot-05-web-admin



#配置mybatis规则
#mybatis:
#  #config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true


# managment 是所有actuator的配置
# managment.endpoint.端点名.xxxx：  对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: true   #默认开启所有监控端点 true
    web:
      exposure:
        include: '*'  #以web方式暴露所有端点

  endpoint:
    health:
      show-details: always
      enabled: true

    info:
      enabled: true

    beans:
      enabled: true

    metrics:
      enabled: true

info:
  appname: boot-admin
  appVersion: 1.0.0
  mavenProjectName: @project.artifactId@
  mavenProjectVersion: @project.version@
